#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGIN_SRC='/opt/local/lib/munin/plugins'
MUNIN_PLUGIN_DST='/opt/local/etc/munin/plugins'
MUNIN_PLUGINS=(
 	'clamav'
 	'spamassassin'
)

# Exit if any commands fail
set -o errexit

echo "* Create clamav logging directory"
mkdir -p /var/log/clamav
chown clamav:clamav /var/log/clamav

# Create extra user for spamd
echo "* Create spamd group and user"
groupadd spamd
useradd -d /var/spamassassin -c "spamassassin spamd user" -s /usr/bin/false -g spamd spamd
passwd -N spamd

# Change default permissions for spamd folder
echo "* Update permissions for spamassassin folders"
mkdir /var/spamassassin/.spamassassin
chown -R spamd:spamd /var/spamassassin
chown -R spamd:spamd /opt/local/etc/spamassassin

# Import spamd manifest
echo "* Import spamd manifest"
svccfg import /tmp/spamd.xml
rm /tmp/spamd.xml

# Update spamd and clamd
echo "* Update spamd and clamd database"
/opt/local/bin/freshclam
pyzor --homedir /opt/local/etc/spamassassin discover

# Configuring image specific packages
echo "* Configuring image specific packages.";

# Use the skylime pkgsrc mirror because it's faster
echo "* Use the skylime pkgsrc mirror because it's faster"
echo "http://pkgsrc.smartos.skylime.net/packages/SmartOS/${PKGSRC_VERSION}/x86_64/All" > /opt/local/etc/pkgin/repositories.conf
pkg_admin rebuild
pkgin -y up

## MUNIN
# Create munin template file that will be used during mdata setup
echo "* Create munin template file that will be used during mdata setup"
cp /opt/local/etc/munin/munin-node.conf /opt/local/etc/munin/munin-node.conf.tpl

# Activate munin plugins
echo "* Activate munin plugins"
for plugin in "${MUNIN_PLUGINS[@]}"; do
	if [ ! -x ${MUNIN_PLUGIN_SRC}/${plugin} ]; then
		plugin_src=${plugin%_*}_
		[ ! -x ${MUNIN_PLUGIN_SRC}/${plugin_src} ] && \
			plugin_src=${plugin_src%%_*}_
	else
		plugin_src=${plugin}
	fi
	if [[ -x ${MUNIN_PLUGIN_SRC}/${plugin_src} ]]; then
		echo "  ${plugin}"
		ln -sf ${MUNIN_PLUGIN_SRC}/${plugin_src} ${MUNIN_PLUGIN_DST}/${plugin}
	fi
done

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
